apiVersion: v1
kind: Pod
metadata:
  name: financial-pipeline-gateway
  namespace: rtf-data-pipline
  labels:
    app: nginx  # Kept as 'nginx' to match your existing Service selector
spec:
  containers:
    - name: pipeline-proxy-container  # Renamed from nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      
