apiVersion: v1
kind: Secret
metadata:
  name: rtf-secret       # Updated name
  namespace: rtf-data-pipeline        # Updated namespace
type: Opaque
stringData:
  # producer
  FINNHUB_API_KEY: "d6vb1b9r01qiiutb5au0d6vb1b9r01qiiutb5aug"

  # S3 data lake
  AWS_ACCESS_KEY: "AKIA54WIFZPMQIO6xxxxx" # your aws access key
  AWS_SECRET_KEY: "PCD0Yi+wgYN1573k1h/2W+lBE8+5lKqSEw+7xxxxx"  # your aws secret key

  # Redshift Creditionals
  REDSHIFT_HOST: "real-time-workgroup-s3.954976291800.us-east-1.redshift-serverless.amazonaws.com"
  REDSHIFT_PORT: "5439"
  REDSHIFT_DB: "dev"
  REDSHIFT_USER: "admin"
  REDSHIFT_PASSWORD: "Qwdgdgdtyuiopionnk" # Redshift Password

  # Snowflake Creditionals
  SNOWFLAKE_USER: "Guru00"  # your snowflake username
  SNOWFLAKE_PASSWORD: "Qwddffyuiohhhhd" # your snowflake password
