apiVersion: v1
kind: Secret
metadata:
  name: rtf-secret       # Updated name
  namespace: rtf-data-pipeline        # Updated namespace
type: Opaque
stringData:
  # producer
  FINNHUB_API_KEY: "d6vb1b9r01qiiutb5au0d6vb1b9r01qiiutb5aug"

  # S3 data lake
  AWS_ACCESS_KEY: "AKIA54WIFZPMPIQIO6V7xxxxx"
  AWS_SECRET_KEY: "PCD0Yi+wgYN156a73k1h/2W+lBE8+5lKqSEw+7m1xxxxx"

  # Redshift Creditionals
  REDSHIFT_HOST: "real-time-workgroup-s3.954976291800.us-east-1.redshift-serverless.amazonaws.com"
  REDSHIFT_PORT: "5439"
  REDSHIFT_DB: "dev"
  REDSHIFT_USER: "admin"
  REDSHIFT_PASSWORD: "Qwertyuiop?01"

  # Snowflake Creditionals
  SNOWFLAKE_USER: "Guru00"
  SNOWFLAKE_PASSWORD: "Qwertyuiop?0101"
